"""empty message

Revision ID: 575312170719
Revises: 8878be47232f
Create Date: 2025-02-14 18:38:01.368509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575312170719'
down_revision = '8878be47232f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_usuario')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turma_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'turma', ['turma_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('turma_id')

    op.create_table('turma_usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('turma_id', sa.INTEGER(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
