"""empty message

Revision ID: 6d4e7a7e4f98
Revises: ab97edcfb9e2
Create Date: 2025-02-21 01:09:56.473898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4e7a7e4f98'
down_revision = 'ab97edcfb9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('turma')
    op.drop_table('material')
    # ### end Alembic commands ###
