"""empty message

Revision ID: 809af83a0013
Revises: ffaabc8c70c3
Create Date: 2025-02-15 00:15:42.289142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809af83a0013'
down_revision = 'ffaabc8c70c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
