"""empty message

Revision ID: 93445e82c54d
Revises: 608c583f59f0
Create Date: 2025-02-07 01:19:16.088722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93445e82c54d'
down_revision = '608c583f59f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma')
    # ### end Alembic commands ###
