"""empty message

Revision ID: ac358627f2eb
Revises: cc58ad11adf1
Create Date: 2025-02-01 15:54:58.361973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac358627f2eb'
down_revision = 'cc58ad11adf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
