"""empty message

Revision ID: cc18e76b5681
Revises: c58abe39c45e
Create Date: 2025-02-14 18:41:31.506728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc18e76b5681'
down_revision = 'c58abe39c45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turma_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'turma', ['turma_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('turma_id')

    # ### end Alembic commands ###
