"""mudando nomes

Revision ID: cc58ad11adf1
Revises: f7b8cdb02d9e
Create Date: 2025-02-01 15:51:12.804431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc58ad11adf1'
down_revision = 'f7b8cdb02d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.Boolean(), nullable=True))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###
