"""Adicionando campo admin na tabela Usuario

Revision ID: f7b8cdb02d9e
Revises: 591f81a59df5
Create Date: 2025-02-01 15:34:25.055408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b8cdb02d9e'
down_revision = '591f81a59df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.INTEGER(), nullable=True))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
